services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - lab-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - lab-network

  config-server:
    container_name: config-server
    build:
      context: ./Back-End/config-server
    image: hikaru420/lab-master-config-server:latest
    ports:
      - "8888:8888"
    environment:
      EUREKA_HOSTNAME: discovery
      MYSQL_HOSTNAME: mysql
      GATEWAY_HOSTNAME: gateway
      LABORATOIRE_HOSTNAME: laboratoire-microservice
      UTILISATEUR_HOSTNAME: utilisateur-microservice
      ANALYSE_HOSTNAME: analyse-microservice
      PATIENT_HOSTNAME: patient-microservice
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lab-network

  discovery:
    container_name: discovery
    build:
      context: ./Back-End/discovery
    image: hikaru420/lab-master-discovery:latest
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lab-network

  gateway:
    container_name: gateway
    build:
      context: ./Back-End/gateway
    image: hikaru420/lab-master-gateway:latest
    ports:
      - "8222:8222"
    depends_on:
      - utilisateur-microservice
    environment:
      GATEWAY_HOSTNAME: gateway
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_HOSTNAME: discovery
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8222/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lab-network

  laboratoire-microservice:
    container_name: laboratoire-microservice
    build:
      context: ./Back-End/laboratoire
    image: hikaru420/lab-master-laboratoire-microservice:latest
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_HOSTNAME: discovery
      MYSQL_HOSTNAME: mysql
      LABORATOIRE_HOSTNAME: analyse-microservice
    depends_on:
      config-server:
        condition: service_healthy
      discovery:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - lab-network

  analyse-microservice:
    container_name: analyse-microservice
    build:
      context: ./Back-End/analyse
    image: hikaru420/lab-master-analyse-microservice:latest
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_HOSTNAME: discovery
      MYSQL_HOSTNAME: mysql
      ANALYSE_HOSTNAME: analyse-microservice
    depends_on:
      config-server:
        condition: service_healthy
      discovery:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - lab-network

  patient-microservice:
    container_name: patient-microservice
    build:
      context: ./Back-End/patient
    image: hikaru420/lab-master-patient-microservice:latest
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_HOSTNAME: discovery
      MYSQL_HOSTNAME: mysql
      PATIENT_HOSTNAME: patient-microservice
    depends_on:
      config-server:
        condition: service_healthy
      discovery:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - lab-network

  utilisateur-microservice:
    container_name: utilisateur-microservice
    build:
      context: ./Back-End/utilisateur
    image: hikaru420/lab-master-utilisateur-microservice:latest
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_HOSTNAME: discovery
      MYSQL_HOSTNAME: mysql
      UTILISATEUR_HOSTNAME: utilisateur-microservice
    depends_on:
      config-server:
        condition: service_healthy
      discovery:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - lab-network

  frontend:
    container_name: frontend
    build:
      context: ./Front-End
    image: hikaru420/lab-master-frontend:latest
    ports:
      - "4200:80"
    depends_on:
      gateway:
        condition: service_healthy
    networks:
      - lab-network

volumes:
  mysql_data:

networks:
  lab-network:
    driver: bridge