
eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: utilisateurs
          uri: http://localhost:8070
          predicates:
            - Path=/api/utilisateurs/**
        - id: laboratoires
          uri: http://localhost:8090
          predicates:
            - Path=/api/laboratoires/**

management:
  tracing:
    sampling:
      probability: 1.0