
eureka:
  instance:
    hostname: ${GATEWAY_HOSTNAME:localhost}
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:8761/eureka
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # To avoid case sensitivity
      routes:

#        - id: laboratoire-microservice
#          uri: lb://laboratoire-microservice
#          predicates:
#            - Path=/api/laboratoires/**

        - id: laboratoire-endpoints
          uri: lb://laboratoire-microservice
          predicates:
            - Path=/api/laboratoires/**

        - id: adresse-endpoints
          uri: lb://laboratoire-microservice
          predicates:
            - Path=/api/adresses/**

        - id: contacts-endpoints
          uri: lb://laboratoire-microservice
          predicates:
            - Path=/api/contacts-laboratoires/**

        - id: utilisateur-microservice
#         uri: http://localhost:8090
          uri: lb://utilisateur-microservice
          predicates:
            - Path=/api/utilisateurs/**

        - id: patient-microservice
          uri: lb://patient-microservice
          predicates:
            - Path=/api/patients/**

        - id: analyse-endpoints
          uri: lb://analyse-microservice
          predicates:
            - Path=/api/analyses/**

        - id: epreuves-endpoints
          uri: lb://analyse-microservice
          predicates:
            - Path=/api/epreuves/**

        - id: testEpreuve-endpoints
          uri: lb://analyse-microservice
          predicates:
            - Path=/api/testEpreuves/**





#      # Configuration CORS to connect Front-End
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "http://${FRONTEND_HOSTNAME:localhost}:4200"
#            allowedMethods: "*"
#            allowedHeaders: "*"
#            allowCredentials: true
application:
  config:
    utilisateurs-url: http://${GATEWAY_HOSTNAME:localhost}:8222/api/utilisateurs

management:
  tracing:
    sampling:
      probability: 1.0