
eureka:
  instance:
    hostname: ${GATEWAY_HOSTNAME:localhost}
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:8761/eureka
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # To avoid case sensitivity
      routes:
      
        - id: laboratoire-microservice
          uri: lb://laboratoire-microservice
#         uri: http://localhost:8070
          predicates:
            - Path=/api/laboratoires/**
        - id: utilisateur-microservice
#         uri: http://localhost:8090
          uri: lb://utilisateur-microservice
          predicates:
            - Path=/api/utilisateurs/**
      # Configuration CORS to connect Front-End
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://${FRONTEND_HOSTNAME:localhost}:4200"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true  

management:
  tracing:
    sampling:
      probability: 1.0