spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: patient-microservice
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  mail:
    host: smtp.gmail.com
    port: 587
    username: elakhirioussama1@gmail.com
    password: cgmu kmoy ljjg bfsk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true