services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ""  # No password for root
      MYSQL_DATABASE: labmaster     # Optional: create a default database
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql_network
    restart: unless-stopped

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql           # MySQL service name
      PMA_PORT: 3306            # MySQL port
      PMA_USER: root            # MySQL username
      PMA_PASSWORD: ""          # No password
    ports:
      - "8080:80"               # Access phpMyAdmin on port 8080
    networks:
      - mysql_network
    restart: unless-stopped

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - zipkin

networks:
  mysql_network:
    driver: bridge
  zipkin:
    driver: bridge

volumes:
  mysql:
  phpmyadmin:
